image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install -r requirements.txt

run:
  script:
    - pip install dist/*whl
  artifacts:
    paths:
      - dist/*.whl

stages:
 - Static Analysis
 - Test

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 --max-complexity 8 raft/src/*.py

pylint:
  stage: Static Analysis
  script:
  - pylint -d C0301 -d R0902 raft/src/*.py

pytest:
  stage: Test
  script:
  - pytest


test:
  script:
    - pip install -r requirements.txt

run:
  script:
    - pip install dist/*whl
  artifacts:
    paths:
      - dist/*.whl

#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc
#    - make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
